name: Build and Push Dashboard Image

on:
    push:
        branches: [ "main" ]
        paths:
            - 'dspm_dashboard/**'
            - 'Dockerfile'
            - '.github/workflows/docker-build.yml'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source
              uses: actions/checkout@v4

            - name: Set up docker Buildx
              uses: docker/setup-buildx-action@v3
            
            - name: Log in to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: comnyang/dashboard:latest
